spring.datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/devstronomy?serverTimezone=UTC
  username: root
  password: root

logging.level:
  root: WARN
  com.devstronomy: INFO

spring:
  config:
    activate:
      on-profile: default
name: "<absolute path to python>"